import Navbar from "@/components/shared/Navbar/page"
import "./globals.css"
import Footer from "@/components/shared/Footer/page"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="font-[raleway]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
